"""cascade project deletion FKs

Revision ID: 31f6049e96fc
Revises: 930c758e5239
Create Date: 2026-07-10 18:32:08.395165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31f6049e96fc'
down_revision: Union[str, None] = '930c758e5239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_logs_project_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tickets_project_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_project_id_fkey'), 'tickets', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_project_id_fkey'), 'activity_logs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
