"""add user full_name

Revision ID: 6e27ac61dab9
Revises: 0452f3b0d67b
Create Date: 2026-07-10 17:49:14.996079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e27ac61dab9'
down_revision: Union[str, None] = '0452f3b0d67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
