"""remove project key column

Revision ID: 930c758e5239
Revises: 6e27ac61dab9
Create Date: 2026-07-10 18:09:36.807118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '930c758e5239'
down_revision: Union[str, None] = '6e27ac61dab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_key'), table_name='projects')
    op.drop_column('projects', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('key', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_projects_key'), 'projects', ['key'], unique=True)
    # ### end Alembic commands ###
