"""cascade delete comments when ticket deleted

Revision ID: ef66d563952f
Revises: ea221015721f
Create Date: 2026-07-10 08:50:26.120643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef66d563952f'
down_revision: Union[str, None] = 'ea221015721f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_ticket_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_ticket_id_fkey'), 'comments', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
